---
title: "MMT"
date: "Julho de 2023"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
# Carregar pacotes ----

library(tidyverse)
library(readr)
library(plotly)
library(treemapify)

quebra <- function(coluna, numPalavras) {
  colunaNova <- character(length(coluna))  # Vetor vazio para armazenar os valores da coluna modificada
  
  for (i in seq_along(coluna)) {
    palavras <- strsplit(coluna[i], " ")[[1]]  # Dividir a célula da coluna em palavras
    resultado <- character(0)  # Vetor vazio para armazenar as palavras
    
    for (j in seq_along(palavras)) {
      resultado <- c(resultado, palavras[j])  # Adicionar cada palavra ao vetor resultado
      
      if (j %% numPalavras == 0 && j != length(palavras)) {
        resultado <- c(resultado, "\n")  # Inserir quebra de linha a cada numPalavras palavras
      }
    }
    
    colunaNova[i] <- paste(resultado, collapse = " ")  # Combinar as palavras novamente em uma única string e atribuir à coluna modificada
  }
  
  return(colunaNova)
}

`%notin%` <- Negate(`%in%`)           # Função de filtro
options(readr.show_col_types = FALSE) # Omitir formato das colunas no console

# Importação dos dados ----

dados_painel2 <- lapply(paste0("../2. Tratamento dos dados/Painel 2 - Remuneração e Ocupações/Resultados/", dir("../2. Tratamento dos dados/Painel 2 - Remuneração e Ocupações/Resultados")), read.csv2)
names(dados_painel2) <- c("ranking_CBO", "remun_media", "num_vinc", "rotatividade")

dados_painel3 <- lapply(paste0("../2. Tratamento dos dados/Painel 3 - Ocupações Técnicas/Resultados/", dir("../2. Tratamento dos dados/Painel 3 - Ocupações Técnicas/Resultados")), read.csv2)
names(dados_painel3) <- c("ocup_cbo", "ocup_emp", "ocup_eixo", "vinc")
```

# Painel 2 - remunerações e ocupações

## Ranking de CBOs

### Ganho de vínculos

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel2$ranking_CBO |>
   mutate(nome_cbo_familia = quebra(nome_cbo_familia, 4)) |>
   arrange(desc(variacao_vinculos)) |>
   slice(1:10) |>
   plot_ly(x = ~variacao_vinculos * 100) |>
   add_trace(y = ~nome_cbo_familia,
             type = "bar",
             color = I("#176180")) |>
   add_annotations(x = ~variacao_vinculos, 
                   y = ~nome_cbo_familia,
                   xanchor = "left",
                   yanchor = "rigth",
                   text = ~paste(round(variacao_vinculos * 100, 2), "%"),
                   textposition = "middle",
                   font = list(color = "white"),
                   showarrow = FALSE) |>
   config(displayModeBar = FALSE) |>
   layout(hovermode = "y",
          yaxis = list(title = "",
                       showgrid = FALSE,
                       showline = TRUE,
                       categoryorder = "total ascending"),
          xaxis = list(title = "",
                       hoverformat = ".1f",
                       showgrid = FALSE,
                       showline = TRUE,
                       ticksuffix = "%"),
          legend = list(orientation = "h",
                        title = list(text = "")),
          barmode = "relative",
          uniformtext = list(minsize = 8,
                             mode = "hide"))
```

### Perda de vínculos

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel2$ranking_CBO |>
   mutate(nome_cbo_familia = quebra(nome_cbo_familia, 4)) |>
   arrange(variacao_vinculos) |>
   slice(1:10) |>
   plot_ly(x = ~variacao_vinculos * 100) |>
   add_trace(y = ~nome_cbo_familia,
             type = "bar",
             color = I("#f04933")) |>
   add_annotations(x = ~variacao_vinculos, 
                   y = ~nome_cbo_familia,
                   xanchor = "right",
                   yanchor = "rigth",
                   text = ~paste(round(variacao_vinculos * 100, 2), "%"),
                   textposition = "middle",
                   font = list(color = "white"),
                   showarrow = FALSE) |>
   config(displayModeBar = FALSE) |>
   layout(hovermode = "y",
          yaxis = list(title = "",
                       showgrid = FALSE,
                       showline = TRUE,
                       categoryorder = "total descending"),
          xaxis = list(title = "",
                       hoverformat = ".1f",
                       showgrid = FALSE,
                       showline = TRUE,
                       ticksuffix = "%"),
          legend = list(orientation = "h",
                        title = list(text = "")),
          barmode = "relative",
          uniformtext = list(minsize = 8,
                             mode = "hide"))
```

### Ganho salarial

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel2$ranking_CBO |>
   mutate(nome_cbo_familia = quebra(nome_cbo_familia, 4)) |>
   arrange(desc(variacao_rendimento)) |>
   slice(1:10) |>
   plot_ly(x = ~variacao_rendimento * 100) |>
   add_trace(y = ~nome_cbo_familia,
             type = "bar",
             color = I("#176180")) |>
   add_annotations(x = ~variacao_rendimento, 
                   y = ~nome_cbo_familia,
                   xanchor = "left",
                   yanchor = "rigth",
                   text = ~paste(round(variacao_rendimento * 100, 2), "%"),
                   textposition = "middle",
                   font = list(color = "white"),
                   showarrow = FALSE) |>
   config(displayModeBar = FALSE) |>
   layout(hovermode = "y",
          yaxis = list(title = "",
                       showgrid = FALSE,
                       showline = TRUE,
                       categoryorder = "total ascending"),
          xaxis = list(title = "",
                       hoverformat = ".1f",
                       showgrid = FALSE,
                       showline = TRUE,
                       ticksuffix = "%"),
          legend = list(orientation = "h",
                        title = list(text = "")),
          barmode = "relative",
          uniformtext = list(minsize = 8,
                             mode = "hide"))
```

### Perda salarial

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel2$ranking_CBO |>
   mutate(nome_cbo_familia = quebra(nome_cbo_familia, 4)) |>
   arrange(variacao_rendimento) |>
   slice(1:10) |>
   plot_ly(x = ~variacao_rendimento * 100) |>
   add_trace(y = ~nome_cbo_familia,
             type = "bar",
             color = I("#f04933")) |>
   add_annotations(x = ~variacao_rendimento, 
                   y = ~nome_cbo_familia,
                   xanchor = "right",
                   yanchor = "rigth",
                   text = ~paste(round(variacao_rendimento * 100, 2), "%"),
                   textposition = "middle",
                   font = list(color = "white"),
                   showarrow = FALSE) |>
   config(displayModeBar = FALSE) |>
   layout(hovermode = "y",
          yaxis = list(title = "",
                       showgrid = FALSE,
                       showline = TRUE,
                       categoryorder = "total descending"),
          xaxis = list(title = "",
                       hoverformat = ".1f",
                       showgrid = FALSE,
                       showline = TRUE,
                       ticksuffix = "%"),
          legend = list(orientation = "h",
                        title = list(text = "")),
          barmode = "relative",
          uniformtext = list(minsize = 8,
                             mode = "hide"))
```

## Remuneração mediana

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel2$remun_media |>
   select(-c(salario_mes, filtro, geral)) |>
   pivot_wider(names_from = tipo,
               values_from = salario_hora) |>
   plot_ly(x = ~ano) |>
   add_trace(y = ~Analfabeto,
             type = "bar",
             name = "Analfabeto",
             color = I("#d92335")) |>
   add_trace(y = ~`Até fundamental completo`,
             type = "bar",
             name = "Até fundamental completo",
             color = I("#064471")) |>
   add_trace(y = ~`Até médio completo`,
             type = "bar",
             name = "Até médio completo",
             color = I("#bd3928")) |>
   add_trace(y = ~`Superior completo*`,
             type = "bar",
             name = "Superior completo",
             color = I("#f87d28")) |>
   add_trace(y = ~`Trabalhadores não técnicos`,
             type = "bar",
             name = "Trabalhadores não técnicos",
             color = I("#0a78c7")) |>
   add_trace(y = ~`Trabalhadores técnicos`,
             type = "bar",
             name = "Trabalhadores técnicos",
             color = I("#fb8e80")) |>
   add_trace(y = ~`Técnicos de nível médio`,
             type = "bar",
             name = "Técnicos de nível médio",
             color = I("#818589")) |>
   add_trace(y = ~`Técnicos de nível superior`,
             type = "bar",
             name = "Técnicos de nível superior",
             color = I("#2b597a")) |>
   config(displayModeBar = FALSE) %>%
   layout(hovermode = "x",
          yaxis = list(title = "",
                       tickprefix = "R$", 
                       hoverformat = '.1f',
                       showgrid = FALSE,
                       showline = TRUE),
          xaxis = list(title = "",
                       tickformat = "%Y",
                       tickmode = "array",
                       tickvals = c(min(dados_painel2$remun_media$ano):max(dados_painel2$remun_media$ano)),
                       showgrid = FALSE,
                       showline = TRUE),
          legend = list(orientation = "h",
                        title = list(text = "")),
          barmode = "group")
```

## Número de vínculos

### Número absoluto

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel2$num_vinc |>
   pivot_wider(names_from = tipo,
               values_from = vinculos) |>
   plot_ly(x = ~ano) |>
   add_trace(y = ~Total,
             type = "scatter", 
             mode = "lines+markers",
             name = "Total",
             color = I("#d92335")) |>
   add_trace(y = ~`Trabalhadores técnicos`,
             type = "scatter", 
             mode = "lines+markers",
             name = "Trabalhadores técnicos",
             color = I("#064471")) |>
   add_trace(y = ~`Trabalhadores não técnicos`,
             type = "scatter", 
             mode = "lines+markers",
             name = "Trabalhadores não técnicos",
             color = I("#bd3928")) |>
config(displayModeBar = FALSE) |>
   layout(hovermode = "x",
          yaxis = list(title = "",
                       hoverformat = ".0f",
                       showgrid = FALSE,
                       showline = TRUE),
          xaxis = list(title = "",
                       tickformat = "%Y",
                       tickmode = "array",
                       tickvals = c(min(dados_painel2$num_vinc$ano):max(dados_painel2$num_vinc$ano)),
                       showgrid = FALSE,
                       showline = TRUE),
          legend = list(orientation = "h",
                        title = list(text = "")),
          barmode = "group")
```

### Taxa de variação

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel2$num_vinc |>
   mutate(variacao = ((vinculos / lag(vinculos, n = 1)) - 1) * 100) |>
   filter(ano > 2011) |>
   pivot_wider(id_cols = -vinculos,
               names_from = tipo,
               values_from = variacao) |>
   plot_ly(x = ~ano) |>
   #add_trace(y = ~Total,
   #          type = "bar",
   #          name = "Total",
   #          color = I("#d92335")) |>
   add_trace(y = ~`Trabalhadores técnicos`,
             type = "bar",
             name = "Trabalhadores técnicos",
             color = I("#064471")) |>
   add_trace(y = ~`Trabalhadores não técnicos`,
             type = "bar",
             name = "Trabalhadores não técnicos",
             color = I("#f87d28")) |>
   config(displayModeBar = FALSE) %>%
   layout(hovermode = "x",
          yaxis = list(title = "",
                       ticksuffix = "%", 
                       hoverformat = '.2f',
                       showgrid = FALSE,
                       showline = TRUE),
          xaxis = list(title = "",
                       tickformat = "%Y",
                       tickmode = "array",
                       tickvals = c(min(dados_painel2$num_vinc$ano):max(dados_painel2$num_vinc$ano)),
                       showgrid = FALSE,
                       showline = TRUE),
          legend = list(orientation = "h",
                        title = list(text = "")),
          barmode = "group")
```

## Taxa de rotatividade

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel2$rotatividade |>
   select(-c(filtro, n_trabalhadores:desligados)) |>
   mutate(rotatividade = rotatividade * 100) |>
   pivot_wider(names_from = tipo,
               values_from = rotatividade) |>
   plot_ly(x = ~anodeclarado) |>
   add_trace(y = ~`Até fundamental completo`,
             type = "scatter", 
             mode = "lines+markers",
             name = "Até fundamental completo",
             color = I("#d92335")) |>
   add_trace(y = ~`Média dos trabalhadores não técnicos`,
             type = "scatter", 
             mode = "lines+markers",
             name = "Média dos trabalhadores não técnicos",
             color = I("#064471")) |>
   add_trace(y = ~`Média dos trabalhadores técnicos`,
             type = "scatter", 
             mode = "lines+markers",
             name = "Média dos trabalhadores técnicos",
             color = I("#bd3928")) |>
   add_trace(y = ~`Médio completo`,
             type = "scatter", 
             mode = "lines+markers",
             name = "Médio completo",
             color = I("#f87d28")) |>
   add_trace(y = ~`Superior completo`,
             type = "scatter", 
             mode = "lines+markers",
             name = "Superior completo",
             color = I("#0a78c7")) |>
   add_trace(y = ~`Técnicos de nível médio`,
             type = "scatter", 
             mode = "lines+markers",
             name = "Técnicos de nível médio",
             color = I("#fb8e80")) |>
   add_trace(y = ~`Técnicos de nível superior`,
             type = "scatter", 
             mode = "lines+markers",
             name = "Técnicos de nível superior",
             color = I("#2b597a")) |>
   config(displayModeBar = FALSE) |>
   layout(hovermode = "x",
          yaxis = list(title = "",
                       ticksuffix = "%",
                       hoverformat = ".2f",
                       showgrid = FALSE,
                       showline = TRUE),
          xaxis = list(title = "",
                       tickformat = "%Y",
                       tickmode = "array",
                       tickvals = c(min(dados_painel2$rotatividade$ano):max(dados_painel2$rotatividade$ano)),
                       showgrid = FALSE,
                       showline = TRUE),
          legend = list(orientation = "h",
                        title = list(text = "")),
          barmode = "group")
```

# Painel 3 - ocupações técnicas

## Ocupações para empresas

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel3$ocup_cbo |>
   filter(nome_cbo_ocupacao == sample(unique(dados_painel3$ocup_cbo$nome_cbo_ocupacao), 1)) |> 
   mutate(label= paste0(nome_cnae_classe,": ",format(vinculos,big.mark = ".",decimal.mark = ","))) |> 
   ggplot(aes(area = vinculos,
              fill = setor_ibge,
              subgroup = setor_ibge,
              subgroup2 = cnae_divisao,
              subgroup3 = cnae_grupo,
              label = label)) +
   geom_treemap() + theme_void()+
   geom_treemap_text(colour = "white" ,size = 13, reflow = T) +
   geom_treemap_subgroup_border(colour = "white", size = 3) +
   geom_treemap_subgroup2_border(colour = "white", size = 1) +
   geom_treemap_subgroup3_border(colour = "white", size = 1) +
   theme(legend.position = "bottom") +
   scale_fill_manual(values = c("#0a78c7","#2b597a","#fb8e80","#f87d28","#bd3928","#d92335")) +
   labs(fill = "Grande Setor IBGE",title = paste("Gráfico para CBO:", sample(unique(dados_painel3$ocup_cbo$nome_cbo_ocupacao), 1)))
```

## Empresas para ocupações

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel3$ocup_emp |>
  filter(nome_cnae_subclasse == sample(unique(dados_painel3$ocup_emp$nome_cnae_subclasse), 1)) |> 
  mutate(label= paste0(nome_cbo_familia, ": ", format(vinculos,big.mark = ".", decimal.mark = ","))) |> 
  ggplot(aes(area = vinculos,fill = nome_cbo_grandegrupo,
             subgroup = nome_cbo_grandegrupo,
             subgroup2 = cbo_subgrupo_principal,
             subgroup3 = cbo_subgrupo, label = label)) +
  treemapify::geom_treemap() + theme_void()+
  treemapify::geom_treemap_text(colour = "white" ,size = 13, reflow = T) +
  treemapify::geom_treemap_subgroup_border(colour = "white", size = 2) +
  treemapify::geom_treemap_subgroup2_border(colour = "white", size = 1) +
  treemapify::geom_treemap_subgroup3_border(colour = "white", size = .5) +
  scale_fill_manual(values = c("#0a78c7","#2b597a","#fb8e80","#00980c",
                               "#bd3928","#d92335","#f87d28","#064471",
                               "#72879d","#e46874","#54a4dc","#e2ccc4","#808080"))+
  labs(fill = "Grande Grupo CBO",title = paste("Gráfico para CBO:", sample(unique(dados_painel3$ocup_emp$nome_cnae_subclasse), 1)))
```

## Ocupações e eixos tecnológicos

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel3$ocup_eixo |>
   mutate(label= paste0(nome_cbo_familia, ": ", format(vinculos,big.mark = ".", decimal.mark = ","))) |>
   ggplot(aes(area = vinculos, 
              fill = eixo, 
              label = label, 
              subgroup = eixo,
              subgroup2 = nome_cbo_subgrupo_principal,
              subgroup3 = nome_cbo_subgrupo)) +
   geom_treemap() + 
   geom_treemap_text(colour = "white", place = "bottomleft",
                     size = 10, reflow = T) +
   geom_treemap_subgroup_border(colour = "white", size = 2.1) +
   geom_treemap_subgroup2_border(colour = "white", size = 1) +
   geom_treemap_subgroup3_border(colour = "white", size = .5) +
   scale_fill_manual(values = c("#0a78c7","#2b597a","#fb8e80","#00980c",
                                "#bd3928","#d92335","#f87d28","#064471",
                                "#72879d","#e46874","#54a4dc","#e2ccc4","#808080"))+
   theme(legend.position = "bottom") +
   labs(fill = "",
        title = "Família de ocupações técnicas do DF por eixo tecnológico")
```

## Remuneração e vínculos

```{r, include=TRUE,echo=FALSE,warning=FALSE,results='asis',fig.align = 'center',fig.dim=c(10,6)}
dados_painel3$vinc |>
   select(cbo_familia,nome_cbo_familia,
          variacao_rendimento,
          variacao_vinculos) |>
   mutate(cat = case_when(variacao_vinculos > 0 & variacao_rendimento > 0 ~ "A",
                          variacao_vinculos < 0 & variacao_rendimento < 0 ~ "B",
                          TRUE ~ "C"),
          variacao_vinculos = round(variacao_vinculos,3),
          variacao_rendimento = round(variacao_rendimento,3)) |> 
   filter(abs(variacao_vinculos) < 1,
          abs(variacao_rendimento) < 1) |>
   plot_ly(x = ~variacao_rendimento * 100,
          y = ~variacao_vinculos * 100,
          color = ~cat,
          colors = c("#0a78c7","#d92335","#fb8e80"),
          text = ~nome_cbo_familia, 
          type = 'scatter', 
          mode = 'markers',
          marker = list(size = 25,opacity = 0.4)) |> 
   config(displayModeBar = FALSE) |>
   layout(yaxis = list(title = "Variação Vínculos",
                       ticksuffix = "%",
                       range=c(-50, 50)),
          xaxis = list(title = "Variação Rendimentos",
                       ticksuffix = "%",
                       range=c(-50, 50)),
          legend = list(orientation = "h",
                        title = list(text = "")))
```
