# Gera tabelas para painel do MMT

# Carrega pacotes
library(data.table)
library(tidyverse)
library(readxl)


# Carregando dados
dados = fread('dados/primario/rais-panorama.csv')
nomes_cnae <- read_excel('dados/estrutura_cbo/cnae_subclasse.xlsx', 
                        sheet = 1, 
                        col_names = TRUE)



# Recortando os dígitos das CBOs
dados[, cbo := as.integer(stringr::str_pad(stringr::str_remove(cboocupacao2002, '-'), width = 6, side = 'left', pad = '0'))  %/% 1e4]


dados$codigo_cbo <- dados$cbo

# Nomes das CBOs Sub Grupo Principal ####
dados[, cbo := fcase(
  cbo	 ==	1	  ,	"MEMBROS DAS FORÇAS ARMADAS",
  cbo	 ==	2	  ,	"POLICIAIS MILITARES",
  cbo	 ==	3	  ,	"BOMBEIROS MILITARES",
  cbo	 ==	11	,	"MEMBROS SUPERIORES E DIRIGENTES DO PODER PÚBLICO",
  cbo	 ==	12	,	"DIRIGENTES DE EMPRESAS E ORGANIZAÇÕES (EXCETO DE INTERESSE PÚBLICO)",
  cbo	 ==	13	,	"DIRETORES E GERENTES EM EMPRESA DE SERVIÇOS DE SAÚDE, DA EDUCAÇÃO, OU DE SERVIÇOS CULTURAIS, SOCIAIS OU PESSOAIS",
  cbo	 ==	14	,	"GERENTES",
  cbo	 ==	20	,	"PESQUISADORES E PROFISSIONAIS POLICIENTÍFICOS",
  cbo	 ==	21	,	"PROFISSIONAIS DAS CIÊNCIAS EXATAS, FÍSICAS E DA ENGENHARIA",
  cbo	 ==	22	,	"PROFISSIONAIS DAS CIÊNCIAS BIOLÓGICAS, DA SAÚDE E AFINS",
  cbo	 ==	23	,	"PROFISSIONAIS DO ENSINO",
  cbo	 ==	24	,	"PROFISSIONAIS DAS CIÊNCIAS JURÍDICAS",
  cbo	 ==	25	,	"PROFISSIONAIS DAS CIÊNCIAS SOCIAIS E HUMANAS",
  cbo	 ==	26	,	"COMUNICADORES, ARTISTAS E RELIGIOSOS",
  cbo	 ==	27	,	"PROFISSIONAIS EM GASTRONOMIA",
  cbo	 ==	30	,	"TÉCNICOS POLIVALENTES",
  cbo	 ==	31	,	"TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS, QUÍMICAS, ENGENHARIA E AFINS",
  cbo	 ==	32	,	"TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS BIOLÓGICAS, BIOQUÍMICAS, DA SAÚDE E AFINS",
  cbo	 ==	33	,	"PROFESSORES LEIGOS E DE NÍVEL MÉDIO",
  cbo	 ==	34	,	"TÉCNICOS DE NÍVEL MÉDIO EM SERVIÇOS DE TRANSPORTES",
  cbo	 ==	35	,	"TÉCNICOS DE NIVEL MÉDIO NAS CIÊNCIAS ADMINISTRATIVAS",
  cbo	 ==	37	,	"TÉCNICOS EM NIVEL MÉDIO DOS SERVIÇOS CULTURAIS, DAS COMUNICAÇÕES E DOS DESPORTOS",
  cbo	 ==	39	,	"OUTROS TÉCNICOS DE NÍVEL MÉDIO",
  cbo	 ==	41	,	"ESCRITURÁRIOS",
  cbo	 ==	42	,	"TRABALHADORES DE ATENDIMENTO AO PÚBLICO",
  cbo	 ==	51	,	"TRABALHADORES DOS SERVIÇOS",
  cbo	 ==	52	,	"VENDEDORES E PRESTADORES DE SERVIÇOS DO COMÉRCIO",
  cbo	 ==	61	,	"PRODUTORES NA EXPLORAÇÃO AGROPECUÁRIA",
  cbo	 ==	62	,	"TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA",
  cbo	 ==	63	,	"PESCADORES E EXTRATIVISTAS FLORESTAIS",
  cbo	 ==	64	,	"TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA E FLORESTAL",
  cbo	 ==	71	,	"TRABALHADORES DA INDÚSTRIA EXTRATIVA E DA CONSTRUÇÃO CIVIL",
  cbo	 ==	72	,	"TRABALHADORES DA TRANSFORMAÇÃO DE METAIS E DE COMPÓSITOS",
  cbo	 ==	73	,	"TRABALHADORES DA FABRICAÇÃO E INSTALAÇÃO ELETROELETRÔNICA",
  cbo	 ==	74	,	"MONTADORES DE APARELHOS E INSTRUMENTOS DE PRECISÃO E MUSICAIS",
  cbo	 ==	75	,	"JOALHEIROS, VIDREIROS, CERAMISTAS E AFINS",
  cbo	 ==	76	,	"TRABALHADORES NAS INDÚSTRIAS TÊXTIL, DO CURTIMENTO, DO VESTÚARIO E DAS ARTES GRÁFICAS",
  cbo	 ==	77	,	"TRABALHADORES DAS INDÚSTRIAS DE MADEIRA E DO MOBILIÁRIO",
  cbo	 ==	78	,	"TRABALHADORES DE FUNÇÕES TRANSVERSAIS",
  cbo	 ==	79	,	"TRABALHADORES DO ARTESANATO",
  cbo	 ==	81	,	"TRABALHADORES EM INDÚSTRIAS DE PROCESSOS CONTÍNUOS E OUTRAS INDÚSTRIAS",
  cbo	 ==	82	,	"TRABALHADORES DE INSTALAÇÕES SIDERÚRGICAS E DE MATERIAIS DE CONSTRUÇÃO",
  cbo	 ==	83	,	"TRABALHADORES DE INSTALAÇÕES E MÁQUINAS DE FABRICAÇÃO DE CELULOSE E PAPEL",
  cbo	 ==	84	,	"TRABALHADORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO",
  cbo	 ==	86	,	"OPERADORES DE PRODUÇÃO, CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO (ENERGIA, ÁGUA E UTILIDADES)",
  cbo	 ==	87	,	"OPERADORES DE OUTRAS INSTALAÇÕES INDUSTRIAIS",
  cbo	 ==	91	,	"TRABALHADORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO MECÂNICA",
  cbo	 ==	95	,	"POLIMANTENEDORES",
  cbo	 ==	99	,	"OUTROS TRABALHADORES DA CONSERVAÇÃO, MANUTENÇÃO E REPARAÇÃO"
)]


# Corrijindo Cnae 2.3 da base ####

dados[dados$cnae20subclasse ==1091101, "cnae20subclasse"] <-1091100
dados[dados$cnae20subclasse ==1091102, "cnae20subclasse"] <-4721101
dados[dados$cnae20subclasse ==1610203, "cnae20subclasse"] <-1610201
dados[dados$cnae20subclasse ==1822901, "cnae20subclasse"] <-1822900
dados[dados$cnae20subclasse ==1822902, "cnae20subclasse"] <-1822900
dados[dados$cnae20subclasse ==1822999, "cnae20subclasse"] <-1822900
dados[dados$cnae20subclasse ==2013401, "cnae20subclasse"] <-2013400
dados[dados$cnae20subclasse ==2539001, "cnae20subclasse"] <-2539000
dados[dados$cnae20subclasse ==3091101, "cnae20subclasse"] <-3091100
dados[dados$cnae20subclasse ==3250709, "cnae20subclasse"] <-3250707
dados[dados$cnae20subclasse ==3511501, "cnae20subclasse"] <-3511500
dados[dados$cnae20subclasse ==3511502, "cnae20subclasse"] <-3511500
dados[dados$cnae20subclasse ==4520008, "cnae20subclasse"] <-4520001
dados[dados$cnae20subclasse ==4541206, "cnae20subclasse"] <-4541205
dados[dados$cnae20subclasse ==4713004, "cnae20subclasse"] <-4713001
dados[dados$cnae20subclasse ==4713005, "cnae20subclasse"] <-4713001
dados[dados$cnae20subclasse ==4729602, "cnae20subclasse"] <-4729699
dados[dados$cnae20subclasse ==4744006, "cnae20subclasse"] <-4744005
dados[dados$cnae20subclasse ==4751201, "cnae20subclasse"] <-4751200
dados[dados$cnae20subclasse ==4751202, "cnae20subclasse"] <-4751200
dados[dados$cnae20subclasse ==5611204, "cnae20subclasse"] <-5611202
dados[dados$cnae20subclasse ==5611205, "cnae20subclasse"] <-5611202
dados[dados$cnae20subclasse ==5812301, "cnae20subclasse"] <-5812300
dados[dados$cnae20subclasse ==5812302, "cnae20subclasse"] <-5812300
dados[dados$cnae20subclasse ==5822101, "cnae20subclasse"] <-5822100
dados[dados$cnae20subclasse ==6201501, "cnae20subclasse"] <-6201500
dados[dados$cnae20subclasse ==6201502, "cnae20subclasse"] <-6201500
dados[dados$cnae20subclasse ==6810203, "cnae20subclasse"] <-6810202
dados[dados$cnae20subclasse ==7410299, "cnae20subclasse"] <-7410202
dados[dados$cnae20subclasse ==8020001, "cnae20subclasse"] <-8020000
dados[dados$cnae20subclasse ==8020002, "cnae20subclasse"] <-8020000
dados[dados$cnae20subclasse ==8690903, "cnae20subclasse"] <-8690901
dados[dados$cnae20subclasse ==8690904, "cnae20subclasse"] <-8690999
dados[dados$cnae20subclasse ==9412001, "cnae20subclasse"] <-9412000
dados[dados$cnae20subclasse ==9412099, "cnae20subclasse"] <-9412000
dados[dados$cnae20subclasse ==9609206, "cnae20subclasse"] <-9609299
dados[dados$cnae20subclasse ==9609207, "cnae20subclasse"] <-9609203
dados[dados$cnae20subclasse ==9609208, "cnae20subclasse"] <-9609203
dados[dados$cnae20subclasse ==4713004, "cnae20subclasse"] <-4713001



# Criação das Bases ####
# Base de vínculos Por cada CBO e CNAE (geral)
base_geral <- dados %>%
  filter(referencia == 2020) %>%
  group_by(cnae20subclasse)%>%
  summarise(tipo_cbo = "geral",
            "MEMBROS DAS FORÇAS ARMADAS" = sum(cbo=="MEMBROS DAS FORÇAS ARMADAS"),
            "POLICIAIS MILITARES" = sum(cbo=="POLICIAIS MILITARES"),
            "BOMBEIROS MILITARES" = sum(cbo=="BOMBEIROS MILITARES"),
            "MEMBROS SUPERIORES E DIRIGENTES DO PODER PÚBLICO" = sum(cbo=="MEMBROS SUPERIORES E DIRIGENTES DO PODER PÚBLICO"),
            "DIRIGENTES DE EMPRESAS E ORGANIZAÇÕES (EXCETO DE INTERESSE PÚBLICO)" = sum(cbo=="DIRIGENTES DE EMPRESAS E ORGANIZAÇÕES (EXCETO DE INTERESSE PÚBLICO)"),
            "DIRETORES E GERENTES EM EMPRESA DE SERVIÇOS DE SAÚDE, DA EDUCAÇÃO, OU DE SERVIÇOS CULTURAIS, SOCIAIS OU PESSOAIS" = sum(cbo=="DIRETORES E GERENTES EM EMPRESA DE SERVIÇOS DE SAÚDE, DA EDUCAÇÃO, OU DE SERVIÇOS CULTURAIS, SOCIAIS OU PESSOAIS"),
            "GERENTES" = sum(cbo=="GERENTES"),
            "PESQUISADORES E PROFISSIONAIS POLICIENTÍFICOS" = sum(cbo=="PESQUISADORES E PROFISSIONAIS POLICIENTÍFICOS"),
            "PROFISSIONAIS DAS CIÊNCIAS EXATAS, FÍSICAS E DA ENGENHARIA" = sum(cbo=="PROFISSIONAIS DAS CIÊNCIAS EXATAS, FÍSICAS E DA ENGENHARIA"),
            "PROFISSIONAIS DAS CIÊNCIAS BIOLÓGICAS, DA SAÚDE E AFINS" = sum(cbo=="PROFISSIONAIS DAS CIÊNCIAS BIOLÓGICAS, DA SAÚDE E AFINS"),
            "PROFISSIONAIS DO ENSINO" = sum(cbo=="PROFISSIONAIS DO ENSINO"),
            "PROFISSIONAIS DAS CIÊNCIAS JURÍDICAS" = sum(cbo=="PROFISSIONAIS DAS CIÊNCIAS JURÍDICAS"),
            "PROFISSIONAIS DAS CIÊNCIAS SOCIAIS E HUMANAS" = sum(cbo=="PROFISSIONAIS DAS CIÊNCIAS SOCIAIS E HUMANAS"),
            "COMUNICADORES, ARTISTAS E RELIGIOSOS" = sum(cbo=="COMUNICADORES, ARTISTAS E RELIGIOSOS"),
            "PROFISSIONAIS EM GASTRONOMIA" = sum(cbo=="PROFISSIONAIS EM GASTRONOMIA"),
            "TÉCNICOS POLIVALENTES" = sum(cbo=="TÉCNICOS POLIVALENTES"),
            "TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS, QUÍMICAS, ENGENHARIA E AFINS" = sum(cbo=="TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS, QUÍMICAS, ENGENHARIA E AFINS"),
            "TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS BIOLÓGICAS, BIOQUÍMICAS, DA SAÚDE E AFINS" = sum(cbo=="TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS BIOLÓGICAS, BIOQUÍMICAS, DA SAÚDE E AFINS"),
            "PROFESSORES LEIGOS E DE NÍVEL MÉDIO" = sum(cbo=="PROFESSORES LEIGOS E DE NÍVEL MÉDIO"),
            "TÉCNICOS DE NÍVEL MÉDIO EM SERVIÇOS DE TRANSPORTES" = sum(cbo=="TÉCNICOS DE NÍVEL MÉDIO EM SERVIÇOS DE TRANSPORTES"),
            "TÉCNICOS DE NIVEL MÉDIO NAS CIÊNCIAS ADMINISTRATIVAS" = sum(cbo=="TÉCNICOS DE NIVEL MÉDIO NAS CIÊNCIAS ADMINISTRATIVAS"),
            "TÉCNICOS EM NIVEL MÉDIO DOS SERVIÇOS CULTURAIS, DAS COMUNICAÇÕES E DOS DESPORTOS" = sum(cbo=="TÉCNICOS EM NIVEL MÉDIO DOS SERVIÇOS CULTURAIS, DAS COMUNICAÇÕES E DOS DESPORTOS"),
            "OUTROS TÉCNICOS DE NÍVEL MÉDIO" = sum(cbo=="OUTROS TÉCNICOS DE NÍVEL MÉDIO"),
            "ESCRITURÁRIOS" = sum(cbo=="ESCRITURÁRIOS"),
            "TRABALHADORES DE ATENDIMENTO AO PÚBLICO" = sum(cbo=="TRABALHADORES DE ATENDIMENTO AO PÚBLICO"),
            "TRABALHADORES DOS SERVIÇOS" = sum(cbo=="TRABALHADORES DOS SERVIÇOS"),
            "VENDEDORES E PRESTADORES DE SERVIÇOS DO COMÉRCIO" = sum(cbo=="VENDEDORES E PRESTADORES DE SERVIÇOS DO COMÉRCIO"),
            "PRODUTORES NA EXPLORAÇÃO AGROPECUÁRIA" = sum(cbo=="PRODUTORES NA EXPLORAÇÃO AGROPECUÁRIA"),
            "TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA" = sum(cbo=="TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA"),
            "PESCADORES E EXTRATIVISTAS FLORESTAIS" = sum(cbo=="PESCADORES E EXTRATIVISTAS FLORESTAIS"),
            "TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA E FLORESTAL" = sum(cbo=="TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA E FLORESTAL"),
            "TRABALHADORES DA INDÚSTRIA EXTRATIVA E DA CONSTRUÇÃO CIVIL" = sum(cbo=="TRABALHADORES DA INDÚSTRIA EXTRATIVA E DA CONSTRUÇÃO CIVIL"),
            "TRABALHADORES DA TRANSFORMAÇÃO DE METAIS E DE COMPÓSITOS" = sum(cbo=="TRABALHADORES DA TRANSFORMAÇÃO DE METAIS E DE COMPÓSITOS"),
            "TRABALHADORES DA FABRICAÇÃO E INSTALAÇÃO ELETROELETRÔNICA" = sum(cbo=="TRABALHADORES DA FABRICAÇÃO E INSTALAÇÃO ELETROELETRÔNICA"),
            "MONTADORES DE APARELHOS E INSTRUMENTOS DE PRECISÃO E MUSICAIS" = sum(cbo=="MONTADORES DE APARELHOS E INSTRUMENTOS DE PRECISÃO E MUSICAIS"),
            "JOALHEIROS, VIDREIROS, CERAMISTAS E AFINS" = sum(cbo=="JOALHEIROS, VIDREIROS, CERAMISTAS E AFINS"),
            "TRABALHADORES NAS INDÚSTRIAS TÊXTIL, DO CURTIMENTO, DO VESTÚARIO E DAS ARTES GRÁFICAS" = sum(cbo=="TRABALHADORES NAS INDÚSTRIAS TÊXTIL, DO CURTIMENTO, DO VESTÚARIO E DAS ARTES GRÁFICAS"),
            "TRABALHADORES DAS INDÚSTRIAS DE MADEIRA E DO MOBILIÁRIO" = sum(cbo=="TRABALHADORES DAS INDÚSTRIAS DE MADEIRA E DO MOBILIÁRIO"),
            "TRABALHADORES DE FUNÇÕES TRANSVERSAIS" = sum(cbo=="TRABALHADORES DE FUNÇÕES TRANSVERSAIS"),
            "TRABALHADORES DO ARTESANATO" = sum(cbo=="TRABALHADORES DO ARTESANATO"),
            "TRABALHADORES EM INDÚSTRIAS DE PROCESSOS CONTÍNUOS E OUTRAS INDÚSTRIAS" = sum(cbo=="TRABALHADORES EM INDÚSTRIAS DE PROCESSOS CONTÍNUOS E OUTRAS INDÚSTRIAS"),
            "TRABALHADORES DE INSTALAÇÕES SIDERÚRGICAS E DE MATERIAIS DE CONSTRUÇÃO" = sum(cbo=="TRABALHADORES DE INSTALAÇÕES SIDERÚRGICAS E DE MATERIAIS DE CONSTRUÇÃO"),
            "TRABALHADORES DE INSTALAÇÕES E MÁQUINAS DE FABRICAÇÃO DE CELULOSE E PAPEL" = sum(cbo=="TRABALHADORES DE INSTALAÇÕES E MÁQUINAS DE FABRICAÇÃO DE CELULOSE E PAPEL"),
            "TRABALHADORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO" = sum(cbo=="TRABALHADORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO"),
            "OPERADORES DE PRODUÇÃO, CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO (ENERGIA, ÁGUA E UTILIDADES)" = sum(cbo=="OPERADORES DE PRODUÇÃO, CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO (ENERGIA, ÁGUA E UTILIDADES)"),
            "OPERADORES DE OUTRAS INSTALAÇÕES INDUSTRIAIS" = sum(cbo=="OPERADORES DE OUTRAS INSTALAÇÕES INDUSTRIAIS"),
            "TRABALHADORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO MECÂNICA" = sum(cbo=="TRABALHADORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO MECÂNICA"),
            "POLIMANTENEDORES" = sum(cbo=="POLIMANTENEDORES"),
            "OUTROS TRABALHADORES DA CONSERVAÇÃO, MANUTENÇÃO E REPARAÇÃO" = sum(cbo=="OUTROS TRABALHADORES DA CONSERVAÇÃO, MANUTENÇÃO E REPARAÇÃO")
  ) %>%
  left_join(dados %>%
              filter(referencia == 2020) %>%
              group_by(cnae20subclasse) %>%
              summarise(viculos = n()), by = "cnae20subclasse")


#Base de vínculos Por cada CBO e CNAE (técnicas)            
base_tecnica <- dados %>%
  filter(referencia == 2020,
         cbo_tec == 1) %>%
  group_by(cnae20subclasse)%>%
  summarise(tipo_cbo = "tecnica",
            "MEMBROS DAS FORÇAS ARMADAS" = sum(cbo=="MEMBROS DAS FORÇAS ARMADAS"),
            "POLICIAIS MILITARES" = sum(cbo=="POLICIAIS MILITARES"),
            "BOMBEIROS MILITARES" = sum(cbo=="BOMBEIROS MILITARES"),
            "MEMBROS SUPERIORES E DIRIGENTES DO PODER PÚBLICO" = sum(cbo=="MEMBROS SUPERIORES E DIRIGENTES DO PODER PÚBLICO"),
            "DIRIGENTES DE EMPRESAS E ORGANIZAÇÕES (EXCETO DE INTERESSE PÚBLICO)" = sum(cbo=="DIRIGENTES DE EMPRESAS E ORGANIZAÇÕES (EXCETO DE INTERESSE PÚBLICO)"),
            "DIRETORES E GERENTES EM EMPRESA DE SERVIÇOS DE SAÚDE, DA EDUCAÇÃO, OU DE SERVIÇOS CULTURAIS, SOCIAIS OU PESSOAIS" = sum(cbo=="DIRETORES E GERENTES EM EMPRESA DE SERVIÇOS DE SAÚDE, DA EDUCAÇÃO, OU DE SERVIÇOS CULTURAIS, SOCIAIS OU PESSOAIS"),
            "GERENTES" = sum(cbo=="GERENTES"),
            "PESQUISADORES E PROFISSIONAIS POLICIENTÍFICOS" = sum(cbo=="PESQUISADORES E PROFISSIONAIS POLICIENTÍFICOS"),
            "PROFISSIONAIS DAS CIÊNCIAS EXATAS, FÍSICAS E DA ENGENHARIA" = sum(cbo=="PROFISSIONAIS DAS CIÊNCIAS EXATAS, FÍSICAS E DA ENGENHARIA"),
            "PROFISSIONAIS DAS CIÊNCIAS BIOLÓGICAS, DA SAÚDE E AFINS" = sum(cbo=="PROFISSIONAIS DAS CIÊNCIAS BIOLÓGICAS, DA SAÚDE E AFINS"),
            "PROFISSIONAIS DO ENSINO" = sum(cbo=="PROFISSIONAIS DO ENSINO"),
            "PROFISSIONAIS DAS CIÊNCIAS JURÍDICAS" = sum(cbo=="PROFISSIONAIS DAS CIÊNCIAS JURÍDICAS"),
            "PROFISSIONAIS DAS CIÊNCIAS SOCIAIS E HUMANAS" = sum(cbo=="PROFISSIONAIS DAS CIÊNCIAS SOCIAIS E HUMANAS"),
            "COMUNICADORES, ARTISTAS E RELIGIOSOS" = sum(cbo=="COMUNICADORES, ARTISTAS E RELIGIOSOS"),
            "PROFISSIONAIS EM GASTRONOMIA" = sum(cbo=="PROFISSIONAIS EM GASTRONOMIA"),
            "TÉCNICOS POLIVALENTES" = sum(cbo=="TÉCNICOS POLIVALENTES"),
            "TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS, QUÍMICAS, ENGENHARIA E AFINS" = sum(cbo=="TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS FÍSICAS, QUÍMICAS, ENGENHARIA E AFINS"),
            "TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS BIOLÓGICAS, BIOQUÍMICAS, DA SAÚDE E AFINS" = sum(cbo=="TÉCNICOS DE NÍVEL MÉDIO DAS CIÊNCIAS BIOLÓGICAS, BIOQUÍMICAS, DA SAÚDE E AFINS"),
            "PROFESSORES LEIGOS E DE NÍVEL MÉDIO" = sum(cbo=="PROFESSORES LEIGOS E DE NÍVEL MÉDIO"),
            "TÉCNICOS DE NÍVEL MÉDIO EM SERVIÇOS DE TRANSPORTES" = sum(cbo=="TÉCNICOS DE NÍVEL MÉDIO EM SERVIÇOS DE TRANSPORTES"),
            "TÉCNICOS DE NIVEL MÉDIO NAS CIÊNCIAS ADMINISTRATIVAS" = sum(cbo=="TÉCNICOS DE NIVEL MÉDIO NAS CIÊNCIAS ADMINISTRATIVAS"),
            "TÉCNICOS EM NIVEL MÉDIO DOS SERVIÇOS CULTURAIS, DAS COMUNICAÇÕES E DOS DESPORTOS" = sum(cbo=="TÉCNICOS EM NIVEL MÉDIO DOS SERVIÇOS CULTURAIS, DAS COMUNICAÇÕES E DOS DESPORTOS"),
            "OUTROS TÉCNICOS DE NÍVEL MÉDIO" = sum(cbo=="OUTROS TÉCNICOS DE NÍVEL MÉDIO"),
            "ESCRITURÁRIOS" = sum(cbo=="ESCRITURÁRIOS"),
            "TRABALHADORES DE ATENDIMENTO AO PÚBLICO" = sum(cbo=="TRABALHADORES DE ATENDIMENTO AO PÚBLICO"),
            "TRABALHADORES DOS SERVIÇOS" = sum(cbo=="TRABALHADORES DOS SERVIÇOS"),
            "VENDEDORES E PRESTADORES DE SERVIÇOS DO COMÉRCIO" = sum(cbo=="VENDEDORES E PRESTADORES DE SERVIÇOS DO COMÉRCIO"),
            "PRODUTORES NA EXPLORAÇÃO AGROPECUÁRIA" = sum(cbo=="PRODUTORES NA EXPLORAÇÃO AGROPECUÁRIA"),
            "TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA" = sum(cbo=="TRABALHADORES NA EXPLORAÇÃO AGROPECUÁRIA"),
            "PESCADORES E EXTRATIVISTAS FLORESTAIS" = sum(cbo=="PESCADORES E EXTRATIVISTAS FLORESTAIS"),
            "TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA E FLORESTAL" = sum(cbo=="TRABALHADORES DA MECANIZAÇÃO AGROPECUÁRIA E FLORESTAL"),
            "TRABALHADORES DA INDÚSTRIA EXTRATIVA E DA CONSTRUÇÃO CIVIL" = sum(cbo=="TRABALHADORES DA INDÚSTRIA EXTRATIVA E DA CONSTRUÇÃO CIVIL"),
            "TRABALHADORES DA TRANSFORMAÇÃO DE METAIS E DE COMPÓSITOS" = sum(cbo=="TRABALHADORES DA TRANSFORMAÇÃO DE METAIS E DE COMPÓSITOS"),
            "TRABALHADORES DA FABRICAÇÃO E INSTALAÇÃO ELETROELETRÔNICA" = sum(cbo=="TRABALHADORES DA FABRICAÇÃO E INSTALAÇÃO ELETROELETRÔNICA"),
            "MONTADORES DE APARELHOS E INSTRUMENTOS DE PRECISÃO E MUSICAIS" = sum(cbo=="MONTADORES DE APARELHOS E INSTRUMENTOS DE PRECISÃO E MUSICAIS"),
            "JOALHEIROS, VIDREIROS, CERAMISTAS E AFINS" = sum(cbo=="JOALHEIROS, VIDREIROS, CERAMISTAS E AFINS"),
            "TRABALHADORES NAS INDÚSTRIAS TÊXTIL, DO CURTIMENTO, DO VESTÚARIO E DAS ARTES GRÁFICAS" = sum(cbo=="TRABALHADORES NAS INDÚSTRIAS TÊXTIL, DO CURTIMENTO, DO VESTÚARIO E DAS ARTES GRÁFICAS"),
            "TRABALHADORES DAS INDÚSTRIAS DE MADEIRA E DO MOBILIÁRIO" = sum(cbo=="TRABALHADORES DAS INDÚSTRIAS DE MADEIRA E DO MOBILIÁRIO"),
            "TRABALHADORES DE FUNÇÕES TRANSVERSAIS" = sum(cbo=="TRABALHADORES DE FUNÇÕES TRANSVERSAIS"),
            "TRABALHADORES DO ARTESANATO" = sum(cbo=="TRABALHADORES DO ARTESANATO"),
            "TRABALHADORES EM INDÚSTRIAS DE PROCESSOS CONTÍNUOS E OUTRAS INDÚSTRIAS" = sum(cbo=="TRABALHADORES EM INDÚSTRIAS DE PROCESSOS CONTÍNUOS E OUTRAS INDÚSTRIAS"),
            "TRABALHADORES DE INSTALAÇÕES SIDERÚRGICAS E DE MATERIAIS DE CONSTRUÇÃO" = sum(cbo=="TRABALHADORES DE INSTALAÇÕES SIDERÚRGICAS E DE MATERIAIS DE CONSTRUÇÃO"),
            "TRABALHADORES DE INSTALAÇÕES E MÁQUINAS DE FABRICAÇÃO DE CELULOSE E PAPEL" = sum(cbo=="TRABALHADORES DE INSTALAÇÕES E MÁQUINAS DE FABRICAÇÃO DE CELULOSE E PAPEL"),
            "TRABALHADORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO" = sum(cbo=="TRABALHADORES DA FABRICAÇÃO DE ALIMENTOS, BEBIDAS E FUMO"),
            "OPERADORES DE PRODUÇÃO, CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO (ENERGIA, ÁGUA E UTILIDADES)" = sum(cbo=="OPERADORES DE PRODUÇÃO, CAPTAÇÃO, TRATAMENTO E DISTRIBUIÇÃO (ENERGIA, ÁGUA E UTILIDADES)"),
            "OPERADORES DE OUTRAS INSTALAÇÕES INDUSTRIAIS" = sum(cbo=="OPERADORES DE OUTRAS INSTALAÇÕES INDUSTRIAIS"),
            "TRABALHADORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO MECÂNICA" = sum(cbo=="TRABALHADORES EM SERVIÇOS DE REPARAÇÃO E MANUTENÇÃO MECÂNICA"),
            "POLIMANTENEDORES" = sum(cbo=="POLIMANTENEDORES"),
            "OUTROS TRABALHADORES DA CONSERVAÇÃO, MANUTENÇÃO E REPARAÇÃO" = sum(cbo=="OUTROS TRABALHADORES DA CONSERVAÇÃO, MANUTENÇÃO E REPARAÇÃO")
  ) %>%
  left_join(dados %>%
              filter(referencia == 2020,
                     cbo_tec == 1) %>%
              group_by(cnae20subclasse) %>%
              summarise(viculos = n()), by = "cnae20subclasse")

# Unindo as bases Geral e Técnica
base <- rbind(base_geral, base_tecnica) %>%
  left_join(nomes_cnae, by = "cnae20subclasse") %>%
  arrange(cnae20subclasse)

readr::write_excel_csv2(base, 'dados/cnae-cbo-vinculos2020.csv')


